apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-singer
  description: The place to be, for great artists
  annotations:
    backstage.io/techdocs-ref: value
spec:
  type: service
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - artist-api
